/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.vistas;

import biblioteca.accesoADatos.EjemplarData;
import biblioteca.accesoADatos.LibroData;
import biblioteca.entidades.Ejemplar;
import biblioteca.entidades.EstadoEjemplar;
import biblioteca.entidades.Libro;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Florencia
 */
public class AgregarEjemplar extends javax.swing.JInternalFrame {

        private LibroData libroData= new LibroData();
        private EjemplarData ejData= new EjemplarData();
        private ArrayList<Libro> listaLibros = new ArrayList<>();
        private ArrayList<Ejemplar> listaEjemplares = new ArrayList<>();
        private DefaultTableModel jtEjemplarModelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    /**
     * Creates new form ListaEjemplares
     */
    public AgregarEjemplar() {
        initComponents();
        armarCabecera();
        //cargarComboBoxLibro();
        cargarComboBoxLibroVacio();
        //cargarComboBoxEstado();
        cargarComboBoxEstadoVacio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbLibro = new javax.swing.JComboBox<>();
        jcbEstado = new javax.swing.JComboBox<>();
        jbAgregar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEj = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGREGAR EJEMPLAR");

        jLabel2.setText("Seleccione un libro");

        jLabel3.setText("Seleccione un estado");

        jcbLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbLibroMouseClicked(evt);
            }
        });
        jcbLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLibroActionPerformed(evt);
            }
        });

        jcbEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbEstadoMouseClicked(evt);
            }
        });
        jcbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoActionPerformed(evt);
            }
        });

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jtEj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtEj);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbLibro, 0, 300, Short.MAX_VALUE)
                    .addComponent(jcbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAgregar))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpiar))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLibroActionPerformed
        // TODO add your handling code here:
        
        
        Libro ejLibro=(Libro)jcbLibro.getModel().getSelectedItem();
        
    }//GEN-LAST:event_jcbLibroActionPerformed

    private void jcbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoActionPerformed
        // TODO add your handling code here:
        
        EstadoEjemplar estadoEj=(EstadoEjemplar)jcbEstado.getModel().getSelectedItem();
        
    }//GEN-LAST:event_jcbEstadoActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        
        Libro ejLibro=(Libro)jcbLibro.getModel().getSelectedItem();
        
        EstadoEjemplar estadoEj=(EstadoEjemplar)jcbEstado.getModel().getSelectedItem();
        
        Ejemplar ejNvo=new Ejemplar();
        
        ejNvo.setLibro(ejLibro);
        ejNvo.setEstado(estadoEj);
        
        ejData.agregarEjemplar(ejNvo);
        
        listaEjemplares.add(ejNvo);

        for (Ejemplar lEj : listaEjemplares) {
            jtEjemplarModelo.addRow(new Object[]{
                lEj.getCodigo(),
                lEj.getLibro().getIsbn(),
                lEj.getLibro().getTitulo(),
                lEj.getLibro().getAutor(),
                lEj.getEstado(),});

        }//finForEach
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jcbLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbLibroMouseClicked
        // TODO add your handling code here:
        cargarComboBoxLibro();
    }//GEN-LAST:event_jcbLibroMouseClicked

    private void jcbEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbEstadoMouseClicked
        // TODO add your handling code here:
        cargarComboBoxEstado();
    }//GEN-LAST:event_jcbEstadoMouseClicked

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        cargarComboBoxLibroVacio();
        cargarComboBoxEstadoVacio();
    }//GEN-LAST:event_jbLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JComboBox<EstadoEjemplar> jcbEstado;
    private javax.swing.JComboBox<Libro> jcbLibro;
    private javax.swing.JTable jtEj;
    // End of variables declaration//GEN-END:variables
    private void armarCabecera() {
        jtEjemplarModelo.addColumn("Código");
        jtEjemplarModelo.addColumn("ISBN");
        jtEjemplarModelo.addColumn("Título");
        jtEjemplarModelo.addColumn("Autor");
        jtEjemplarModelo.addColumn("Estado");

        jtEj.setModel(jtEjemplarModelo);
    }
    
    private void cargarComboBoxEstadoVacio() {
        jcbEstado.setModel(new DefaultComboBoxModel<>());
    }
    
    private void cargarComboBoxEstado(){
        jcbEstado.setModel(new DefaultComboBoxModel<>(EstadoEjemplar.values()));
    }

    private void cargarComboBoxLibroVacio() {
        jcbLibro.setModel(new DefaultComboBoxModel<>());
    }

    private void cargarComboBoxLibro(){
        listaLibros=libroData.listarLibros();
        
        for (int i = 0; i < listaLibros.size(); i++) {
            
            jcbLibro.addItem(listaLibros.get(i));
        }
    }

    private void borrarFilas() {
        int f = jtEj.getRowCount() - 1;

        for (; f >= 0; f--) {
            jtEjemplarModelo.removeRow(f);
        }
    }
}
