/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.vistas;

/**
 *
 * @author agus_
 */
public class biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form biblioteca
     */
    public biblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmLector = new javax.swing.JMenu();
        jmGestionLectores = new javax.swing.JMenuItem();
        jmLibro = new javax.swing.JMenu();
        jmAniadirLibro = new javax.swing.JMenuItem();
        jmGestionLibros = new javax.swing.JMenuItem();
        jmListarLibros = new javax.swing.JMenuItem();
        jmListaEjemplares = new javax.swing.JMenu();
        jmBuscarEjemplar = new javax.swing.JMenuItem();
        jmAgregarEjemplar = new javax.swing.JMenuItem();
        jmActualizarEjemplar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmPrestamo = new javax.swing.JMenu();
        jmPrestarLibro = new javax.swing.JMenuItem();
        jmDevolverLibro = new javax.swing.JMenuItem();
        jmGestionPrestamos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        jmLector.setText("Lector");

        jmGestionLectores.setText("Gestion de lectores");
        jmGestionLectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGestionLectoresActionPerformed(evt);
            }
        });
        jmLector.add(jmGestionLectores);

        jMenuBar1.add(jmLector);

        jmLibro.setText("Libro");

        jmAniadirLibro.setText("Añadir libro");
        jmAniadirLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAniadirLibroActionPerformed(evt);
            }
        });
        jmLibro.add(jmAniadirLibro);

        jmGestionLibros.setText("Gestion de libros");
        jmGestionLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGestionLibrosActionPerformed(evt);
            }
        });
        jmLibro.add(jmGestionLibros);

        jmListarLibros.setText("Listar libros");
        jmListarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarLibrosActionPerformed(evt);
            }
        });
        jmLibro.add(jmListarLibros);

        jMenuBar1.add(jmLibro);

        jmListaEjemplares.setText("Ejemplar");

        jmBuscarEjemplar.setText("Buscar Ejemplar");
        jmBuscarEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarEjemplarActionPerformed(evt);
            }
        });
        jmListaEjemplares.add(jmBuscarEjemplar);

        jmAgregarEjemplar.setText("Agregar Ejemplar");
        jmAgregarEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarEjemplarActionPerformed(evt);
            }
        });
        jmListaEjemplares.add(jmAgregarEjemplar);

        jmActualizarEjemplar.setText("Actualizar Ejemplar");
        jmActualizarEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmActualizarEjemplarActionPerformed(evt);
            }
        });
        jmListaEjemplares.add(jmActualizarEjemplar);

        jMenuItem2.setText("Lista de Ejemplares");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmListaEjemplares.add(jMenuItem2);

        jMenuBar1.add(jmListaEjemplares);

        jmPrestamo.setText("Prestamo");

        jmPrestarLibro.setText("Prestar libro");
        jmPrestarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPrestarLibroActionPerformed(evt);
            }
        });
        jmPrestamo.add(jmPrestarLibro);

        jmDevolverLibro.setText("Devolver libro");
        jmDevolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDevolverLibroActionPerformed(evt);
            }
        });
        jmPrestamo.add(jmDevolverLibro);

        jmGestionPrestamos.setText("Gestion de prestamos");
        jmGestionPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGestionPrestamosActionPerformed(evt);
            }
        });
        jmPrestamo.add(jmGestionPrestamos);

        jMenuBar1.add(jmPrestamo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmGestionLectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGestionLectoresActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        GestionLectores gLectores = new GestionLectores();
        gLectores.setVisible(true);
        Escritorio.add(gLectores);
        Escritorio.moveToFront(gLectores);
    }//GEN-LAST:event_jmGestionLectoresActionPerformed

    private void jmAniadirLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAniadirLibroActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        GestionLibros gLibros = new GestionLibros();
        gLibros.setVisible(true);
        Escritorio.add(gLibros);
        Escritorio.moveToFront(gLibros);
    }//GEN-LAST:event_jmAniadirLibroActionPerformed

    private void jmBuscarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarEjemplarActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        BuscarEjemplar gEjemplares = new BuscarEjemplar();
        gEjemplares.setVisible(true);
        Escritorio.add(gEjemplares);
        Escritorio.moveToFront(gEjemplares);
    }//GEN-LAST:event_jmBuscarEjemplarActionPerformed

    private void jmPrestarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPrestarLibroActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        PrestarLibro pl = new PrestarLibro();
        pl.setVisible(true);
        Escritorio.add(pl);
        Escritorio.moveToFront(pl);
    }//GEN-LAST:event_jmPrestarLibroActionPerformed

    private void jmDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDevolverLibroActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        DevolverLibro dl = new DevolverLibro();
        dl.setVisible(true);
        Escritorio.add(dl);
        Escritorio.moveToFront(dl);
    }//GEN-LAST:event_jmDevolverLibroActionPerformed

    private void jmGestionLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGestionLibrosActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        ModificarLibro mLibros = new ModificarLibro();
        mLibros.setVisible(true);
        Escritorio.add(mLibros);
        Escritorio.moveToFront(mLibros);
    }//GEN-LAST:event_jmGestionLibrosActionPerformed

    private void jmListarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarLibrosActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        ListaLibros lLibros = new ListaLibros();
        lLibros.setVisible(true);
        Escritorio.add(lLibros);
        Escritorio.moveToFront(lLibros);
    }//GEN-LAST:event_jmListarLibrosActionPerformed

    private void jmGestionPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGestionPrestamosActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        BusquedaPrestamos bp = new BusquedaPrestamos();
        bp.setVisible(true);
        Escritorio.add(bp);
        Escritorio.moveToFront(bp);
    }//GEN-LAST:event_jmGestionPrestamosActionPerformed

    private void jmAgregarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarEjemplarActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        AgregarEjemplar agregarEjemplar = new AgregarEjemplar();
        agregarEjemplar.setVisible(true);
        Escritorio.add(agregarEjemplar);
        Escritorio.moveToFront(agregarEjemplar);
    }//GEN-LAST:event_jmAgregarEjemplarActionPerformed

    private void jmActualizarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmActualizarEjemplarActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        ActualizarEjemplar aj = new ActualizarEjemplar();
        aj.setVisible(true);
        Escritorio.add(aj);
        Escritorio.moveToFront(aj);
    }//GEN-LAST:event_jmActualizarEjemplarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        ListaEjemplares le = new ListaEjemplares();
        le.setVisible(true);
        Escritorio.add(le);
        Escritorio.moveToFront(le);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmActualizarEjemplar;
    private javax.swing.JMenuItem jmAgregarEjemplar;
    private javax.swing.JMenuItem jmAniadirLibro;
    private javax.swing.JMenuItem jmBuscarEjemplar;
    private javax.swing.JMenuItem jmDevolverLibro;
    private javax.swing.JMenuItem jmGestionLectores;
    private javax.swing.JMenuItem jmGestionLibros;
    private javax.swing.JMenuItem jmGestionPrestamos;
    private javax.swing.JMenu jmLector;
    private javax.swing.JMenu jmLibro;
    private javax.swing.JMenu jmListaEjemplares;
    private javax.swing.JMenuItem jmListarLibros;
    private javax.swing.JMenu jmPrestamo;
    private javax.swing.JMenuItem jmPrestarLibro;
    // End of variables declaration//GEN-END:variables
}
