/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.vistas;

import biblioteca.accesoADatos.LibroData;
import biblioteca.entidades.Libro;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class ModificarLibro extends javax.swing.JInternalFrame {

    private LibroData libroData = new LibroData();
    private List<Libro> libros;
    /**
     * Creates new form ModificarLibro
     */
    public ModificarLibro() {
        initComponents();
        armarCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcISBN = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtTitulo = new javax.swing.JTextField();
        jtAutor = new javax.swing.JTextField();
        jtAnio = new javax.swing.JTextField();
        jtTipo = new javax.swing.JTextField();
        jtEditorial = new javax.swing.JTextField();
        jbModificar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jrEstado = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DE LIBROS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ISBN");

        jcISBN.setEditable(true);
        jcISBN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcISBNMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcISBNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcISBNMouseEntered(evt);
            }
        });
        jcISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcISBNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Titulo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Autor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Año");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tipo");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Editorial");

        jtTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtAutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtAnio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtEditorial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jbModificar.setText("MODIFICAR");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbSalir.setText("SALIR");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcISBN, 0, 270, Short.MAX_VALUE)
                            .addComponent(jtTitulo)
                            .addComponent(jtAutor)
                            .addComponent(jtAnio)
                            .addComponent(jtTipo)
                            .addComponent(jtEditorial)
                            .addComponent(jrEstado)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbModificar)
                        .addGap(176, 176, 176)
                        .addComponent(jbSalir)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jrEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificar)
                    .addComponent(jbSalir))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcISBNActionPerformed
        // TODO add your handling code here:
        Libro libro = libroData.buscarLibroXIsbn((int)jcISBN.getModel().getSelectedItem());
        
        jrEstado.setSelected(libro.isEstado());
        jtAnio.setText(libro.getAnio()+"");
        jtAutor.setText(libro.getAutor());
        jtEditorial.setText(libro.getEditorial());
        jtTipo.setText(libro.getTipo());
        jtTitulo.setText(libro.getTitulo());
    }//GEN-LAST:event_jcISBNActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        try {
            String titulo = jtTitulo.getText();
        String autor = jtAutor.getText();
        int anio = Integer.parseInt(jtAnio.getText());
        String tipo = jtTipo.getText();
        String editor = jtEditorial.getText();
        boolean estad = jrEstado.isSelected();
            if (titulo.equals("") || autor.equals("") || tipo.equals("") || editor.equals("")) {
                JOptionPane.showMessageDialog(null, "Error al ingresar los datos.");
                JOptionPane.showMessageDialog(null, "Verifique que todos los parametros tienen datos.");
            } else {
                Libro libro = new Libro((int)jcISBN.getModel().getSelectedItem(), titulo, autor, anio, tipo, editor, estad);
                libroData.modificarLibro(libro);
                limpiar();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error al ingresar nuevos datos.");
            JOptionPane.showMessageDialog(null, "En el campo 'Año' debe ir un numero entero.");
        }
        
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jcISBNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcISBNMouseClicked
        
    }//GEN-LAST:event_jcISBNMouseClicked

    private void jcISBNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcISBNMousePressed
       
    }//GEN-LAST:event_jcISBNMousePressed

    private void jcISBNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcISBNMouseEntered
        
    }//GEN-LAST:event_jcISBNMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Integer> jcISBN;
    private javax.swing.JRadioButton jrEstado;
    private javax.swing.JTextField jtAnio;
    private javax.swing.JTextField jtAutor;
    private javax.swing.JTextField jtEditorial;
    private javax.swing.JTextField jtTipo;
    private javax.swing.JTextField jtTitulo;
    // End of variables declaration//GEN-END:variables
 private void armarCombobox(){
     
     libros = libroData.listarTodoLibros();
     
     for (Libro libro : libros) {
         jcISBN.addItem(libro.getIsbn());
     }
 }
 private void limpiar(){
     jtAnio.setText("");
     jtAutor.setText("");
     jtEditorial.setText("");
     jtTipo.setText("");
     jtTitulo.setText("");
     jrEstado.setSelected(false);
 }
}

