/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package biblioteca.vistas;

import biblioteca.accesoADatos.*;
import biblioteca.entidades.*;
import java.awt.event.ItemEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.*;

/**
 *
 * @author agus_
 */
public class PrestarLibro extends javax.swing.JInternalFrame {

    private PrestamoData pd = new PrestamoData();
    private LectorData ld = new LectorData();
    private EjemplarData ed = new EjemplarData();
    private LibroData libroD = new LibroData();
    private List<Lector> lectores = new ArrayList<>();
    private List<Libro> libros = new ArrayList<>();
    private List<Ejemplar> ejemplares = new ArrayList<>();

    /**
     * Creates new form GestionPrestamos
     */
    public PrestarLibro() {
        initComponents();
        armarComboBoxLectores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbLectores = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcbLibros = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcbEjemplares = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jDatePrestamo = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateDevolucion = new com.toedter.calendar.JDateChooser();
        jbPrestar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(800, 300));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRESTAR LIBRO");

        jLabel2.setText("Lector: ");

        jcbLectores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbLectoresItemStateChanged(evt);
            }
        });

        jLabel3.setText("Libro: ");

        jcbLibros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbLibrosItemStateChanged(evt);
            }
        });

        jLabel4.setText("Ejemplares diponibles: ");

        jLabel5.setText("Fecha de prestamo:");

        jLabel6.setText("Fecha de devolucion:");

        jbPrestar.setText("Prestar");
        jbPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrestarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbPrestar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbLibros, 0, 429, Short.MAX_VALUE)
                                    .addComponent(jcbLectores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDatePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jDateDevolucion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jcbEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbLectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDatePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jbPrestar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbLectoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbLectoresItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jcbLibros.removeAllItems();
            armarComboBoxLibros();
        }
    }//GEN-LAST:event_jcbLectoresItemStateChanged

    private void jcbLibrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbLibrosItemStateChanged
        Libro libro = (Libro) jcbLibros.getSelectedItem();
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jcbEjemplares.removeAllItems();
            armarComboBoxEjemplares();
        }
    }//GEN-LAST:event_jcbLibrosItemStateChanged

    private void jbPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrestarActionPerformed
        Lector lector = (Lector) jcbLectores.getSelectedItem();
        Ejemplar ejemplar = (Ejemplar) jcbEjemplares.getSelectedItem();
        Date fechaP = jDatePrestamo.getDate();
        Date fechaD = jDateDevolucion.getDate();
        
        LocalDate ldPrestamo = fechaP.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate ldDevolucion = fechaD.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        Prestamo prestamo = new Prestamo(ldPrestamo, ldDevolucion, ejemplar, lector, true);
        
        pd.prestarLibro(prestamo);
    }//GEN-LAST:event_jbPrestarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateDevolucion;
    private com.toedter.calendar.JDateChooser jDatePrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbPrestar;
    private javax.swing.JComboBox<Ejemplar> jcbEjemplares;
    private javax.swing.JComboBox<Lector> jcbLectores;
    private javax.swing.JComboBox<Libro> jcbLibros;
    // End of variables declaration//GEN-END:variables

    private void armarComboBoxLectores() {
        lectores = ld.listarLectores();

        for (Lector lector : lectores) {
            jcbLectores.addItem(lector);
        }
    }

    private void armarComboBoxLibros() {
        libros = libroD.listarLibros();

        for (Libro libro : libros) {
            jcbLibros.addItem(libro);
        }
    }

    private void armarComboBoxEjemplares() {
        Libro libro = (Libro) jcbLibros.getSelectedItem();
        
        ejemplares = ed.listarEjemplaresXLibro(libro);

        for (Ejemplar ejemplar : ejemplares) {
            jcbEjemplares.addItem(ejemplar);
        }
    }
    
}
